-- MySQL Script generated by MySQL Workbench
-- sex 02 abr 2021 19:19:51 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema survey
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `survey` DEFAULT CHARACTER SET utf8 ;
USE `survey` ;

-- -----------------------------------------------------
-- Table `survey`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`pessoa` (
  `cod_pessoa` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`animal_estimacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL AUTO_INCREMENT,
  `animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`),
  UNIQUE INDEX `cod_animal_estimacao_UNIQUE` (`cod_animal_estimacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`bebida` (
  `cod_bebida` INT NOT NULL AUTO_INCREMENT,
  `bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`clima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`clima` (
  `cod_clima` INT NOT NULL AUTO_INCREMENT,
  `clima` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`hobbie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`hobbie` (
  `cod_hobbie` INT NOT NULL AUTO_INCREMENT,
  `hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `survey`.`pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `survey`.`pesquisa` (
  `cod_pesquisa` INT NOT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NOT NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  `cod_hobbie` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_pesquisa_pessoa_idx` (`cod_pessoa` ASC),
  INDEX `fk_pesquisa_animal_estimacao1_idx` (`cod_animal_estimacao` ASC),
  INDEX `fk_pesquisa_bebida1_idx` (`cod_bebida` ASC),
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC),
  INDEX `fk_pesquisa_hobbie1_idx` (`cod_hobbie` ASC),
  CONSTRAINT `fk_pesquisa_pessoa`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `survey`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_animal_estimacao1`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `survey`.`animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `survey`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `survey`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `survey`.`hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
